### ISSUE TITLE
Write scripts to generate INSERT queries

### ISSUE THREAD

**Issue by Huy-Ngo** [dinhanhx/TV_series_management#2]
Since the database is fairly large, we would need to write a script to generate these statements.

**Comment by Huy-Ngo** [comment]
Hey I don't see any progress. Still busy?

**Comment by dinhanhx** [comment]
I put Computer Network in higher priority so this will be likely carried out right after Morning Friday.

**Comment by dinhanhx** [comment]
@DDHLong You write script to insert into table genres and series_genres.

**Comment by dinhanhx** [comment]
@dinhanhx read [this](https://github.com/dinhanhx/TV_series_management/commit/3446a8536d55bce22ea9d5aa7970d9c908a3f95f#comments)
